### PR TITLE
made the sequence argument of type 'uint16_t const *'

### PR DESCRIPTION
**Pull request by NESFreak**
I need to send an adc a static command. As it resides in flash, it has signature `uint16_t const cmd[]`. As the library doesn't write to the TX sequence buffer, there's no reason I can imagine why the sequence argument can't be of type 'uint16_t const *'

Note, I considered making it `restricted` as well, but actually having the TX and RX buffers overlap works and saves ram ;-).

### CODE REVIEW

**Comment by jwr** [comment]
You are right, the library never writes to the sequence, only stores a pointer to it and reads from it. I rarely strive for const correctness, though.

I would merge this, but I don't have a running CCS setup to check — does this generate any additional warnings for you elsewhere in the code?

**Comment by NESFreak** [comment]
Compiles and runs fine with TI v17.3.0.STS:

```
**** Build of configuration Debug for project usitest ****

"C:\\ti\\ccsv7\\utils\\bin\\gmake" -k -j 4 all -O 
'Building file: ../main.c'
'Invoking: MSP430 Compiler'
"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/bin/cl430" -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/Jeroen/workspace_v7/usitest" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/include" --advice:power=all --define=__MSP430F2013__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="main.d"  "../main.c"
"../main.c", line 17: remark #1527-D: (ULP 2.1) Detected SW delay loop using empty loop. Recommend using a timer module instead
"../main.c", line 33: remark #1527-D: (ULP 2.1) Detected SW delay loop using __delay_cycles. Recommend using a timer module instead
'Finished building: ../main.c'
' '
'Building file: ../usi_i2c.c'
'Invoking: MSP430 Compiler'
"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/bin/cl430" -vmsp --use_hw_mpy=none --include_path="C:/ti/ccsv7/ccs_base/msp430/include" --include_path="C:/Users/Jeroen/workspace_v7/usitest" --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/include" --advice:power=all --define=__MSP430F2013__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="usi_i2c.d"  "../usi_i2c.c"
"../usi_i2c.c", line 40: remark #1527-D: (ULP 2.1) Detected SW delay loop using empty loop. Recommend using a timer module instead
"../usi_i2c.c", line 93: remark #1538-D: (ULP 10.1) ISR USI_TXRX calls function i2c_prepare_data_xmit_recv. Recommend moving function call away from ISR, or inlining the function, or using pragmas
"../usi_i2c.c", line 104: remark #1538-D: (ULP 10.1) ISR USI_TXRX calls function i2c_prepare_stop. Recommend moving function call away from ISR, or inlining the function, or using pragmas
"../usi_i2c.c", line 106: remark #1538-D: (ULP 10.1) ISR USI_TXRX calls function i2c_prepare_data_xmit_recv. Recommend moving function call away from ISR, or inlining the function, or using pragmas
"../usi_i2c.c", line 126: remark #1538-D: (ULP 10.1) ISR USI_TXRX calls function i2c_prepare_stop. Recommend moving function call away from ISR, or inlining the function, or using pragmas
'Finished building: ../usi_i2c.c'
' '
'Building target: usitest.out'
'Invoking: MSP430 Linker'
"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/bin/cl430" -vmsp --use_hw_mpy=none --advice:power=all --define=__MSP430F2013__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number -z -m"usitest.map" --heap_size=0 --stack_size=50 -i"C:/ti/ccsv7/ccs_base/msp430/include" -i"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/lib" -i"C:/ti/ccsv7/tools/compiler/ti-cgt-msp430_17.3.0.STS/include" --reread_libs --diag_wrap=off --display_error_number --warn_sections --xml_link_info="usitest_linkInfo.xml" --use_hw_mpy=none --rom_model -o "usitest.out" "./main.obj" "./usi_i2c.obj" "../lnk_msp430f2013.cmd"  -llibc.a 
<Linking>
remark #10371-D: (ULP 1.1) Detected no uses of low power mode state changing instructions
'Finished building target: usitest.out'
' '

**** Build Finished ****
```

However, for the sake of completeness I decided to build with mspgcc (5.3.0.224) as well, however that one fails on the USI interrupt:
```
#pragma vector = USI_VECTOR
__interrupt void USI_TXRX(void)
```
```
../usi_i2c.c:82:0: warning: ignoring #pragma vector  [-Wunknown-pragmas]
 #pragma vector = USI_VECTOR
 ^
../usi_i2c.c:83:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
 __interrupt void USI_TXRX(void)
             ^
```
I have fixed this by instead using
```
#ifdef __GNUC__
__attribute__((interrupt(USI_VECTOR)))
#else
#pragma vector = USI_VECTOR
__interrupt
#endif
void USI_TXRX(void)
```

Furthermore I noticed you explicitly including `msp430g2412.h` instead of the generic `msp430.h`, though everything worked fine even though I am using the f2013 chip.

Would you like me to submit a pull request for any of these fixes as well?

**Comment by jwr** [comment]
Yes, please submit a pull request for these two fixes as well, and thank you for putting in this effort. As I wrote, I don't have a setup for building MSP430 code, and my time is very limited, so I will gladly take these patches.

> Furthermore I noticed you explicitly including msp430g2412.h instead of the generic msp430.h, though everything worked fine even though I am using the f2013 chip.

No reason for that, it's accidental — that's the chip I used. The code should work on any MSP430 with an USI peripheral.

Thank you for checking the warnings, too!

**Comment by NESFreak** [comment]
Thank you for accepting. And for writing this lib in the first place. I got quite some headaches trying to understand the logic behind the official `msp430x20x3_usi_*.c` examples.
